[build]
command = "npm run production"
publish = "dist"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' //www.google-analytics.com //instant.page //identity.netlify.com //unpkg.com //www.youtube.com //player.vimeo.com"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin"
Feature-Policy = "geolocation none"
cache-control = '''
max-age=604800,
public'''