[build]
command = "npm run production"
publish = "dist"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' google-analytics.com instant.page $.netlify.com unpkg.com youtube.com $.vimeo.com"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin"
Feature-Policy = "geolocation none"

[[headers]]
for = "/images*"

[headers.values]
cache-control = '''
max-age=604800,
public'''