[build]
command = "npm run production"
publish = "dist"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://www.google-analytics.com https://instant.page"