[build]
  command = "npm run production"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; font-src 'self'; img-src 'self'; object-src 'self'; script-src 'self' https://www.google-analytics.com https://instant.page; style-src 'self'"